basePath: /conductor/v1/api
definitions:
  response.ContaResponse:
    properties:
      id:
        type: string
      status:
        type: string
    type: object
  response.TransacaoResponse:
    properties:
      descricao:
        type: string
      id:
        type: string
      id_conta:
        type: string
      valor:
        type: number
    type: object
host: localhost:8080
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: This is a sample server Petstore server.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Swagger Example API
  version: "1.0"
paths:
  /contas:
    get:
      consumes:
      - application/json
      description: Retorna a lista com todas as contas
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/response.ContaResponse'
            type: array
      summary: Obter contas
  /contas/{id}:
    get:
      consumes:
      - application/json
      description: Retorna a lista com todas as contas
      parameters:
      - description: Id da conta
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/response.ContaResponse'
            type: array
      summary: Obter contas por id
  /contas/{id}/transacoes:
    get:
      consumes:
      - application/json
      description: Retorna a lista com todas as transações da conta
      parameters:
      - description: Id da conta
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/response.TransacaoResponse'
            type: array
      summary: Obter transações da conta
  /contas/{id}/transacoes.pdf:
    get:
      consumes:
      - application/json
      description: Download de relatório com todas as transações da conta
      parameters:
      - description: Id da conta
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/pdf
      responses:
        "200":
          description: OK
          schema:
            type: integer
      summary: Obter contas
swagger: "2.0"
